baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'GDTF & MVR Help Pages'
theme = 'hugo-theme-relearn-7.6.1'

[params]
  linkTitle = 'Help Pages'
  disableLandingPageButton = false
  themeVariant = ["light", "dark"]
  hideAuthorDate = true
  ordersectionsby = 'weight'
  collapsibleMenu = true
  alwaysopen = false

[markup.goldmark]
  renderer.unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
